(function () {
  'use strict';
  var API_BASE_URL = 'https://otw-clevvo-api-competitions-cb45ebb65abc.herokuapp.com/api';
  var ENDPOINTS = { calendars: '/public/competition-data-v2/calendars', rankings: '/public/competition-data-v2/rankings' };
  var cachedMatches = null;

  function escapeHtml(value) { return String(value === undefined || value === null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
  function firstValue(object, keys) { for (var i = 0; i < keys.length; i += 1) { if (object && object[keys[i]] !== undefined && object[keys[i]] !== null && object[keys[i]] !== '') return object[keys[i]]; } return null; }
  function collectionFrom(data, keys) { var content = data && data.content !== undefined ? data.content : data; if (Array.isArray(content)) return content; for (var i = 0; i < keys.length; i += 1) if (Array.isArray(content && content[keys[i]])) return content[keys[i]]; return []; }
  function formatDate(value) { var date = new Date(value); return Number.isNaN(date.getTime()) ? 'Data por confirmar' : new Intl.DateTimeFormat('pt-PT', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(date); }
  function formatTime(value) { var date = new Date(value); return Number.isNaN(date.getTime()) ? 'Hora por confirmar' : new Intl.DateTimeFormat('pt-PT', { hour: '2-digit', minute: '2-digit' }).format(date); }
  function activeTab() { var active = document.querySelector('.tab-button.active'); return active ? active.id.replace('tab-', '') : 'calendario'; }
  function matchCompetition(match) { return firstValue(match, ['competitionName', 'competition', 'competitionDescription']) || 'Competição'; }
  function matchCategory(match) { return firstValue(match, ['categoryDescription', 'category']) || 'Outros'; }
  function matchPhase(match) { return [firstValue(match, ['phaseName', 'phase']), firstValue(match, ['phaseGroupName', 'phaseGroup', 'groupName'])].filter(Boolean).join(' · '); }
  function hasResult(match) { var score = firstValue(match, ['score', 'result']); return score && score !== 'Aguardar' && score !== '-'; }
  function matchDetailsHref(match) { return 'jogo.html?calendarId=' + encodeURIComponent(match.id) + '&returnTo=' + encodeURIComponent('competicoes.html?tab=' + activeTab()); }

  function teamLink(match, side) {
    var home = side === 'home'; var name = firstValue(match, home ? ['homeTeam', 'homeTeamName'] : ['awayTeam', 'awayTeamName']) || 'Equipa por confirmar';
    var teamId = firstValue(match, home ? ['homeTeamId'] : ['awayTeamId']);
    if (!teamId || String(teamId) !== String(match.sourceTeamId)) return escapeHtml(name);
    var href = 'equipa.html?teamId=' + encodeURIComponent(teamId) + '&teamName=' + encodeURIComponent(name) + '&category=' + encodeURIComponent(matchCategory(match)) + '&returnTo=' + encodeURIComponent('competicoes.html?tab=' + activeTab());
    return '<a class="team-link" href="' + href + '" title="Abrir área da equipa ' + escapeHtml(name) + '">' + escapeHtml(name) + '<i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i></a>';
  }
  function renderMatch(match, result) {
    var homeHighlighted = match.isHomeTeamHighlighted === true; var score = firstValue(match, ['score', 'result']); var scoreDisplay = result && score ? String(score).replace('(NO)', '') : '—'; var phase = matchPhase(match);
    var scoreMarkup = result && match.id ? '<a class="match-score-link" href="' + matchDetailsHref(match) + '" aria-label="Ver detalhes do jogo: ' + escapeHtml(scoreDisplay) + '" title="Ver detalhes do jogo"><span>' + escapeHtml(scoreDisplay) + '</span><i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i></a>' : '<span>' + escapeHtml(scoreDisplay) + '</span>';
    return '<article class="match-card ' + (homeHighlighted ? 'bg-emerald-50' : 'bg-gray-50') + ' rounded-xl p-4 transition"><div class="grid grid-cols-1 lg:grid-cols-[200px_1fr_200px] items-center gap-4"><div class="flex items-center gap-3"><div class="w-10 h-10 ' + (homeHighlighted ? 'bg-emerald-700' : 'bg-gray-400') + ' rounded-full flex items-center justify-center flex-shrink-0"><i class="fa-solid ' + (result ? 'fa-futbol' : 'fa-calendar-days') + ' text-white text-sm"></i></div><div><p class="text-sm text-gray-700 font-semibold capitalize">' + escapeHtml(formatDate(match.date)) + '</p><p class="text-xs text-gray-500">' + escapeHtml(formatTime(match.date)) + '</p></div></div><div class="match-teams flex items-center justify-center gap-4"><div class="text-right flex-1 min-w-0"><p class="font-bold text-gray-900 text-sm">' + teamLink(match, 'home') + '</p><p class="text-xs text-gray-500">Casa</p></div><div class="px-4 py-2 bg-white rounded-lg shadow-sm flex-shrink-0 min-w-[60px] text-center"><p class="font-bold ' + (homeHighlighted ? 'text-emerald-700' : 'text-gray-700') + ' text-base">' + scoreMarkup + '</p></div><div class="text-left flex-1 min-w-0"><p class="font-bold text-gray-900 text-sm">' + teamLink(match, 'away') + '</p><p class="text-xs text-gray-500">Fora</p></div></div><div class="text-center lg:text-right"><p class="text-sm font-semibold text-gray-900">' + escapeHtml(matchCompetition(match)) + '</p><p class="competition-meta">' + escapeHtml(phase || match.stadium || '') + '</p>' + (match.fixtureDescription ? '<p class="competition-meta">' + escapeHtml(match.fixtureDescription) + '</p>' : '') + '</div></div></article>';
  }
  function state(container, icon, message, retry) { container.innerHTML = '<div class="text-center py-12"><i class="fa-solid ' + icon + ' text-4xl text-emerald-700 mb-3"></i><p class="text-gray-600">' + escapeHtml(message) + '</p>' + (retry ? '<button type="button" data-retry class="mt-4 px-4 py-2 bg-emerald-700 text-white rounded-lg">Tentar novamente</button>' : '') + '</div>'; var button = container.querySelector('[data-retry]'); if (button) button.addEventListener('click', retry); }
  async function matches() { if (cachedMatches) return cachedMatches; var response = await fetch(API_BASE_URL + ENDPOINTS.calendars); if (!response.ok) throw new Error('calendars request failed'); cachedMatches = collectionFrom(await response.json(), ['matches', 'items', 'calendars']); return cachedMatches; }
  function compareDatesNewestFirst(a, b) { return new Date(b.date).getTime() - new Date(a.date).getTime(); }
  function renderGroups(list, result) { var categories = list.reduce(function (all, match) { var category = matchCategory(match); var categoryId = Number(firstValue(match, ['categoryId']) || Number.MAX_SAFE_INTEGER); var phase = matchPhase(match); var competitionId = String(firstValue(match, ['competitionId', 'idCompetition']) || '') + '|' + phase; if (!all[category]) all[category] = { id: categoryId, competitions: {} }; if (!all[category].competitions[competitionId]) all[category].competitions[competitionId] = { name: [matchCompetition(match), phase].filter(Boolean).join(' · '), matches: [] }; all[category].competitions[competitionId].matches.push(match); return all; }, {}); return Object.keys(categories).sort(function (a, b) { return categories[a].id - categories[b].id || a.localeCompare(b, 'pt'); }).map(function (category) { var competitions = categories[category].competitions; return '<section class="mb-7"><h3 class="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2"><i class="fa-solid fa-layer-group text-emerald-700"></i>' + escapeHtml(category) + '</h3>' + Object.keys(competitions).sort(function (a, b) { return competitions[a].name.localeCompare(competitions[b].name, 'pt'); }).map(function (competitionId) { var competition = competitions[competitionId]; competition.matches.sort(compareDatesNewestFirst); return '<section class="mb-5"><h4 class="text-base font-bold text-emerald-800 mb-3">' + escapeHtml(competition.name) + '</h4><div class="space-y-3">' + competition.matches.map(function (match) { return renderMatch(match, result); }).join('') + '</div></section>'; }).join('') + '</section>'; }).join(''); }
  async function loadCalendarData() { var container = document.getElementById('calendar-matches'); state(container, 'fa-spinner fa-spin', 'A carregar calendário...'); try { var list = (await matches()).filter(function (match) { return !hasResult(match); }); if (!list.length) state(container, 'fa-calendar-xmark', 'Não há jogos agendados.'); else container.innerHTML = renderGroups(list, false); } catch (error) { console.error(error); state(container, 'fa-triangle-exclamation', 'Não foi possível carregar o calendário.', loadCalendarData); } }
  async function loadResultsData() { var container = document.getElementById('results-matches'); state(container, 'fa-spinner fa-spin', 'A carregar resultados...'); try { var list = (await matches()).filter(hasResult); if (!list.length) state(container, 'fa-futbol', 'Não há resultados disponíveis.'); else container.innerHTML = renderGroups(list, true); } catch (error) { console.error(error); state(container, 'fa-triangle-exclamation', 'Não foi possível carregar os resultados.', loadResultsData); } }

  function flattenRankings(value, rows) { if (Array.isArray(value)) { value.forEach(function (item) { flattenRankings(item, rows); }); return; } if (!value || typeof value !== 'object') return; if (firstValue(value, ['position', 'rank']) !== null && firstValue(value, ['clubDescription', 'teamName', 'clubName']) !== null) { rows.push(value); return; } ['items', 'rankings', 'standings', 'groups', 'phases', 'competitions', 'categories'].forEach(function (key) { if (value[key]) flattenRankings(value[key], rows); }); }
  function standingName(row) { var name = firstValue(row, ['clubDescription', 'teamName', 'clubName', 'description']) || 'Equipa'; var teamId = firstValue(row, ['teamId', 'sourceTeamId']); if (!row.isHighlightedRow || !teamId) return escapeHtml(name); var href = 'equipa.html?teamId=' + encodeURIComponent(teamId) + '&teamName=' + encodeURIComponent(name) + '&category=' + encodeURIComponent(firstValue(row, ['categoryDescription', 'category']) || '') + '&returnTo=' + encodeURIComponent('competicoes.html?tab=classificacao'); return '<a class="team-link" href="' + href + '">' + escapeHtml(name) + '<i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i></a>'; }
  function renderRankingsTable(rows) { var headers = ['Pos', 'Clube', 'J', 'V', 'E', 'D', 'GM', 'GS', 'DG', 'Pts']; var keys = [['position', 'rank'], null, ['matches', 'matchesPlayed', 'numberOfMatches'], ['wins'], ['draws'], ['losses'], ['goalsScored'], ['goalsAgainst', 'goalsConceded'], ['goalsDifference', 'goalDifference'], ['points']]; var lastPosition = 0; rows.sort(function (a, b) { return Number(firstValue(a, ['position', 'rank'])) - Number(firstValue(b, ['position', 'rank'])); }); return '<div class="bg-white rounded-xl shadow-md overflow-x-auto"><table class="w-full min-w-[680px]"><thead class="bg-emerald-700 text-white"><tr>' + headers.map(function (header) { return '<th class="px-3 py-3 text-center text-sm">' + header + '</th>'; }).join('') + '</tr></thead><tbody class="divide-y divide-gray-200">' + rows.map(function (row) { var sourcePosition = Number(firstValue(row, ['position', 'rank'])); var displayedPosition = Number.isFinite(sourcePosition) && sourcePosition > lastPosition ? sourcePosition : lastPosition + 1; lastPosition = displayedPosition; return '<tr class="' + (row.isHighlightedRow ? 'bg-emerald-50 font-semibold' : 'bg-white hover:bg-gray-50') + '">' + keys.map(function (key, index) { if (index === 1) return '<td class="px-4 py-3 text-left text-sm">' + (row.isHighlightedRow ? '<i class="fa-solid fa-star text-emerald-700 mr-2"></i>' : '') + standingName(row) + '</td>'; var value = index === 0 ? displayedPosition : firstValue(row, key); return '<td class="px-3 py-3 text-center text-sm ' + (index === 9 ? 'font-bold text-emerald-700' : '') + '">' + (index === 8 && Number(value) > 0 ? '+' : '') + escapeHtml(value === null ? '—' : value) + '</td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table></div>'; }
  function renderRankings(rows) { var groups = rows.reduce(function (all, row) { var category = firstValue(row, ['categoryDescription', 'category']) || 'Outros'; var competition = firstValue(row, ['competitionName', 'competitionDescription']) || 'Competição'; var stage = [firstValue(row, ['phaseName', 'phase']), firstValue(row, ['phaseGroupName', 'phaseGroup', 'groupName'])].filter(Boolean).join(' · '); var key = category + '|' + (firstValue(row, ['competitionId', 'idCompetition']) || '') + '|' + stage; if (!all[key]) all[key] = { category: category, categoryId: Number(firstValue(row, ['categoryId']) || Number.MAX_SAFE_INTEGER), competition: competition, stage: stage, rows: [] }; all[key].rows.push(row); return all; }, {}); return Object.keys(groups).map(function (key) { return groups[key]; }).sort(function (a, b) { return a.categoryId - b.categoryId || a.competition.localeCompare(b.competition, 'pt') || a.stage.localeCompare(b.stage, 'pt') || a.category.localeCompare(b.category, 'pt'); }).map(function (group) { return '<section class="mb-8"><h3 class="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2"><i class="fa-solid fa-trophy text-emerald-700"></i>' + escapeHtml([group.category, group.competition, group.stage].filter(Boolean).join(' · ')) + '</h3>' + renderRankingsTable(group.rows) + '</section>'; }).join(''); }
  async function loadClassificationData() { var container = document.getElementById('classification-tables'); state(container, 'fa-spinner fa-spin', 'A carregar classificações...'); try { var response = await fetch(API_BASE_URL + ENDPOINTS.rankings); if (!response.ok) throw new Error('rankings request failed'); var data = await response.json(); var rows = []; flattenRankings(data.content, rows); if (!rows.length) state(container, 'fa-table-list', 'Não há classificações disponíveis.'); else container.innerHTML = renderRankings(rows); } catch (error) { console.error(error); state(container, 'fa-triangle-exclamation', 'Não foi possível carregar as classificações.', loadClassificationData); } }
  window.showTab = function (name) { document.querySelectorAll('.tab-content').forEach(function (content) { content.classList.add('hidden'); }); document.querySelectorAll('.tab-button').forEach(function (button) { button.classList.remove('active', 'bg-white', 'text-emerald-700'); button.classList.add('bg-white/20', 'text-white'); button.setAttribute('aria-selected', 'false'); }); document.getElementById('content-' + name).classList.remove('hidden'); var button = document.getElementById('tab-' + name); button.classList.add('active', 'bg-white', 'text-emerald-700'); button.classList.remove('bg-white/20', 'text-white'); button.setAttribute('aria-selected', 'true'); var url = new URL(window.location.href); url.searchParams.set('tab', name); window.history.replaceState({}, '', url); if (name === 'calendario') loadCalendarData(); else if (name === 'classificacao') loadClassificationData(); else loadResultsData(); };
  document.addEventListener('DOMContentLoaded', function () { var requested = new URLSearchParams(window.location.search).get('tab'); window.showTab(['calendario', 'classificacao', 'resultados'].indexOf(requested) !== -1 ? requested : 'calendario'); });
}());
