(function () {
  'use strict';
  var API_BASE_URL = 'https://otw-clevvo-api-competitions-cb45ebb65abc.herokuapp.com/api';
  var container = document.getElementById('match-details');
  var modal = document.getElementById('match-player-modal');
  var modalContent = document.getElementById('match-player-content');
  var lastFocus = null;

  function escapeHtml(value) { return String(value === undefined || value === null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
  function formatDate(value) { var date = new Date(value); return Number.isNaN(date.getTime()) ? 'Data por confirmar' : new Intl.DateTimeFormat('pt-PT', { weekday:'long', day:'numeric', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit' }).format(date); }
  function initials(name) { return String(name || '?').trim().split(/\s+/).slice(0, 2).map(function (part) { return part.charAt(0); }).join('').toUpperCase(); }
  function safeReturnPath() { var value = new URLSearchParams(window.location.search).get('returnTo'); return value && !/^[a-z][a-z0-9+.-]*:/i.test(value) && value.indexOf('//') !== 0 ? value : 'competicoes.html?tab=resultados'; }
  function state(icon, message) { container.innerHTML = '<div class="match-state"><i class="fa-solid ' + icon + '"></i><p>' + escapeHtml(message) + '</p></div>'; }
  function score(match) { return match.score ? String(match.score).replace('(NO)', '') : '—'; }
  function eventIcon(event) { if (event.sourceType === 'MatchPart') return ['fa-flag-checkered', '']; if (event.matchEventTypeId === 4) return ['fa-futbol', 'timeline-event__icon--goal']; if (event.matchEventTypeId === 2 || event.matchEventTypeId === 6) return ['fa-square', 'timeline-event__icon--card']; if (event.matchEventTypeId === 3) return ['fa-square', 'timeline-event__icon--red']; return ['fa-right-left', '']; }
  function eventLabel(event, players) { var player = players[event.playerId]; var out = players[event.playerOutId]; if (event.sourceType === 'MatchPart') { if (String(event.externalItemId) === '1') return 'Fim da 1.ª parte'; if (String(event.externalItemId) === '2') return 'Fim do jogo'; return 'Fim da parte'; } if (event.matchEventTypeId === 1) return (player ? player.name : 'Jogador') + ' entra por ' + (out ? out.name : 'jogador'); return (player ? player.name : 'Jogador') + ' · ' + (event.matchEventType || 'Acontecimento'); }
  function eventMinute(event) { return event.minute === null || event.minute === undefined ? '' : event.minute + (event.extraMinute ? '+' + event.extraMinute : '') + '′'; }
  function matchPartTime(event) { if (event.minute === null || event.minute === undefined) return ''; var part = String(event.externalItemId) === '2' ? 2 : 1; var minute = String((Number(event.minute) || 0) * part) + '′'; return event.extraMinute ? minute + ' + ' + String(event.extraMinute) + '′ de descontos' : minute; }
  function timelineOrder(event) { var part = String(event.externalItemId); if (event.sourceType === 'MatchPart' && part === '1') return 45999; if (event.sourceType === 'MatchPart' && part === '2') return Number.MAX_SAFE_INTEGER; return (Number(event.minute) || 0) * 1000 + (Number(event.extraMinute) || 0); }
  function orderedTimeline(timeline) { return timeline.map(function (event, index) { return { event:event, index:index }; }).sort(function (a, b) { return timelineOrder(a.event) - timelineOrder(b.event) || a.index - b.index; }).map(function (item) { return item.event; }); }
  function renderTimeline(timeline, match, players) { if (!timeline.length) return '<p class="lineup-empty">Ainda não há acontecimentos disponíveis.</p>'; return '<div class="timeline">' + orderedTimeline(timeline).map(function (event) { var icon = eventIcon(event); if (event.sourceType === 'MatchPart') { var partTime = matchPartTime(event); return '<div class="timeline-break"><i class="fa-solid ' + icon[0] + '"></i> ' + escapeHtml(eventLabel(event, players)) + (partTime ? '<span>' + escapeHtml(partTime) + '</span>' : '') + '</div>'; } var side = String(event.teamId) === String(match.homeTeamId) ? 'timeline-event--home' : 'timeline-event--away'; var scoreText = event.homeScore === null || event.homeScore === undefined ? '' : event.homeScore + ' - ' + event.awayScore; return '<article class="timeline-event ' + side + '"><span class="timeline-event__minute">' + escapeHtml(eventMinute(event)) + '</span><span class="timeline-event__icon ' + icon[1] + '"><i class="fa-solid ' + icon[0] + '"></i></span><span class="timeline-event__text">' + escapeHtml(eventLabel(event, players)) + '</span><span class="timeline-event__score">' + escapeHtml(scoreText) + '</span></article>'; }).join('') + '</div>'; }
  function playerButton(player) { var photo = player.photoUrl ? '<img class="lineup-player__photo" src="' + escapeHtml(player.photoUrl) + '" alt="Fotografia de ' + escapeHtml(player.name) + '">' : '<span class="lineup-player__fallback">' + escapeHtml(initials(player.name)) + '</span>'; var badges = (player.captain ? '<i class="fa-solid fa-c" title="Capitão"></i>' : '') + (player.goalkeeper ? '<i class="fa-solid fa-hand" title="Guarda-redes"></i>' : ''); return '<button class="lineup-player" type="button" data-player-id="' + escapeHtml(player.playerId) + '"><span class="lineup-player__number">' + escapeHtml(player.jerseyNumber || '—') + '</span>' + photo + '<span>' + escapeHtml(player.name) + '</span><span class="lineup-player__badges">' + badges + '</span></button>'; }
  function renderLineup(teamName, players) { var starters = players.filter(function (player) { return player.startingTeam; }); var bench = players.filter(function (player) { return !player.startingTeam; }); return '<section class="lineup-team"><h3>' + escapeHtml(teamName) + '</h3><p class="lineup-label">Onze inicial</p><div class="lineup-list">' + (starters.length ? starters.map(playerButton).join('') : '<p class="lineup-empty">Não disponível</p>') + '</div><p class="lineup-label">Suplentes</p><div class="lineup-list">' + (bench.length ? bench.map(playerButton).join('') : '<p class="lineup-empty">Não disponível</p>') + '</div></section>'; }
  function teamIdentity(name, logoUrl, side) { var logo = logoUrl ? '<img src="' + escapeHtml(logoUrl) + '" alt="Emblema de ' + escapeHtml(name) + '">' : '<span aria-hidden="true">' + escapeHtml(initials(name)) + '</span>'; return '<div class="match-scoreboard__team match-scoreboard__team--' + side + '"><span class="match-scoreboard__crest">' + logo + '</span><strong>' + escapeHtml(name) + '</strong></div>'; }
  function renderReferees(referees) { if (!referees.length) return ''; return '<div class="match-officials"><span class="match-officials__label"><i class="fa-solid fa-whistle" aria-hidden="true"></i> Equipa de arbitragem</span><span class="match-officials__names">' + referees.map(function (referee) { return escapeHtml(referee.refereeName || referee.name || 'Árbitro'); }).join('<b aria-hidden="true">·</b>') + '</span></div>'; }
  function render(details) {
    var match = details.match; var players = {};
    (details.lineups || []).forEach(function (player) { players[player.playerId] = player; });
    var phase = [match.phaseName, match.phaseGroupName].filter(Boolean).join(' · ');
    var homePlayers = (details.lineups || []).filter(function (player) { return String(player.teamId) === String(match.homeTeamId); });
    var awayPlayers = (details.lineups || []).filter(function (player) { return String(player.teamId) === String(match.awayTeamId); });
    container.innerHTML = '<section class="match-hero"><p class="match-competition">' + escapeHtml([match.categoryDescription, match.competitionName, phase].filter(Boolean).join(' · ')) + '</p><h1>' + escapeHtml(match.fixtureDescription || 'Detalhes do jogo') + '</h1><div class="match-scoreboard">' + teamIdentity(match.homeTeam || 'Equipa da casa', match.homeTeamLogoUrl, 'home') + '<div class="match-scoreboard__score">' + escapeHtml(score(match)) + '<small>Resultado final</small></div>' + teamIdentity(match.awayTeam || 'Equipa visitante', match.awayTeamLogoUrl, 'away') + '</div><div class="match-meta"><span><i class="fa-solid fa-calendar-days"></i>' + escapeHtml(formatDate(match.date)) + '</span><span><i class="fa-solid fa-location-dot"></i>' + escapeHtml(match.stadium || 'Local por confirmar') + '</span></div>' + renderReferees(details.referees || []) + '</section><section class="match-section match-details-tabs"><div class="match-tablist" role="tablist" aria-label="Detalhes do jogo"><button class="match-tab is-active" type="button" role="tab" aria-selected="true" aria-controls="match-panel-timeline" id="match-tab-timeline" data-match-tab="timeline"><i class="fa-solid fa-timeline" aria-hidden="true"></i> Cronologia</button><button class="match-tab" type="button" role="tab" aria-selected="false" aria-controls="match-panel-lineups" id="match-tab-lineups" data-match-tab="lineups"><i class="fa-solid fa-people-group" aria-hidden="true"></i> Alinhamentos</button></div><div id="match-panel-timeline" class="match-tab-panel" role="tabpanel" aria-labelledby="match-tab-timeline">' + renderTimeline(details.timeline || [], match, players) + '</div><div id="match-panel-lineups" class="match-tab-panel" role="tabpanel" aria-labelledby="match-tab-lineups" hidden><div class="lineups">' + renderLineup(match.homeTeam, homePlayers) + renderLineup(match.awayTeam, awayPlayers) + '</div></div></section>';
    container.querySelectorAll('[data-player-id]').forEach(function (button) { button.addEventListener('click', function () { openPlayer(players[button.dataset.playerId]); }); });
    container.querySelectorAll('[data-match-tab]').forEach(function (button) { button.addEventListener('click', function () { var target = button.dataset.matchTab; container.querySelectorAll('[data-match-tab]').forEach(function (tab) { var active = tab === button; tab.classList.toggle('is-active', active); tab.setAttribute('aria-selected', active ? 'true' : 'false'); }); container.querySelectorAll('.match-tab-panel').forEach(function (panel) { panel.hidden = panel.id !== 'match-panel-' + target; }); }); });
  }
  function closePlayer() { if (modal.hidden) return; modal.hidden = true; document.body.style.overflow = ''; if (lastFocus) lastFocus.focus(); }
  async function openPlayer(player) {
    if (!player) return; lastFocus = document.activeElement; modalContent.innerHTML = '<article><section class="match-player-card__hero">' + (player.photoUrl ? '<img class="match-player-card__photo" src="' + escapeHtml(player.photoUrl) + '" alt="Fotografia de ' + escapeHtml(player.name) + '">' : '<div class="match-player-card__fallback">' + escapeHtml(initials(player.name)) + '</div>') + '<h2 id="match-player-name">' + escapeHtml(player.name) + '</h2><p>N.º ' + escapeHtml(player.jerseyNumber || '—') + (player.captain ? ' · Capitão' : '') + '</p></section><section class="match-player-card__body"><h3>Destaques da época</h3><div class="player-match-stats" id="match-player-stats"><p class="lineup-empty">A carregar estatísticas...</p></div></section></article>'; modal.hidden = false; document.body.style.overflow = 'hidden'; modal.querySelector('.match-player-modal__card').focus();
    try { var response = await fetch(API_BASE_URL + '/public/scouting/players/' + encodeURIComponent(player.playerId) + '/statistics'); if (!response.ok) throw new Error('statistics'); var data = await response.json(); var totals = data.content && data.content.totals ? data.content.totals : {}; document.getElementById('match-player-stats').innerHTML = [['Jogos', totals.numberOfMatchesPlayed], ['Minutos', totals.minutes], ['Golos', totals.goalsScored]].map(function (stat) { return '<div class="player-match-stat"><strong>' + escapeHtml(stat[1] === null || stat[1] === undefined ? '—' : stat[1]) + '</strong><span>' + stat[0] + '</span></div>'; }).join(''); } catch (error) { document.getElementById('match-player-stats').innerHTML = '<p class="lineup-empty">Estatísticas indisponíveis.</p>'; }
  }
  async function load() { document.getElementById('match-back').href = safeReturnPath(); var id = new URLSearchParams(window.location.search).get('calendarId'); if (!id || !/^\d+$/.test(id)) { state('fa-circle-exclamation', 'Não foi possível identificar o jogo.'); return; } state('fa-spinner fa-spin', 'A carregar detalhes do jogo...'); try { var response = await fetch(API_BASE_URL + '/public/competition-data-v2/calendars/' + encodeURIComponent(id) + '/details'); if (!response.ok) throw new Error('details'); var data = await response.json(); if (!data.content || !data.content.match) throw new Error('empty'); render(data.content); } catch (error) { console.error('Error loading match details:', error); state('fa-triangle-exclamation', 'Não foi possível carregar os detalhes deste jogo.'); } }
  document.querySelectorAll('[data-close-player-modal]').forEach(function (item) { item.addEventListener('click', closePlayer); }); document.addEventListener('keydown', function (event) { if (event.key === 'Escape') closePlayer(); }); document.addEventListener('DOMContentLoaded', load);
}());
